### ISSUE TITLE
incorrect threshold due to lack of float precision ?

### ISSUE THREAD

**Issue by blinard-BIOINFO** [phylo42/IPK#12]
This is a general problem due to the fact that pow(float,float) is not precise enough ?

The computed threshold return a float superior to the expected value.
Below, k=4, omega=8.
Expected thresold = (8/20)⁴ = 0.0256

```
# I get the values from xpas db
for (const auto& [f, p, m] : *entries)
[...]

# get the threshold in the xpas way, this return a float
auto _thr = xpas::score_threshold(_db.omega(), _db.kmer_size());
auto _thr_log = std::log10(_thr);   

# for some reason, xpas return a float threshold > to the expected value
# p = -1.59176004 
# _thr = 0.0256000012     (why ?)
# _thr_log = -1.59176004
```

**Comment by nromashchenko** [comment]
This the reality of IEEE 754. The best you can do is to ignore it. Please refer to these informative illustrations: [one](https://cdn.hashnode.com/res/hashnode/image/upload/v1676097792232/b90787dd-e815-4c3c-95ab-0fc28ae5c9ac.png), [two](https://i.imgflip.com/6iy40i.jpg), [three](https://img.ifunny.co/images/323ee4fc0abdc84d9321025a4c0d3e32310b66f4297b3532f49de04daca6f4f9_1.webp).
