### ISSUE TITLE
Unmentioned/undocumented python dependency

### ISSUE THREAD

**Issue by lczech** [phylo42/IPK#17]
Hi again,

I'm seeing unmet dependencies when executing IPK:

    ModuleNotFoundError: No module named 'click'

A simple `pip3 install click` does the trick, but this should be documented :-)

I think there might be other python dependencies that I am not getting as I already have them installed. I suggest to test in clean VMs for some operating systems, or even better, use GitHub Actions or another CI tool to do that for you every time you push code to the repo!

Cheers
Lucas

**Comment by nromashchenko** [comment]
Thanks! [Closed](https://github.com/phylo42/IPK/pull/22).
