### ISSUE TITLE
phyml-mpi issue

### ISSUE THREAD

**Issue by woodford87** [phylo42/IPK#2]
Hello, 

I'm trying to run xpas for the first time and I am getting the following error:

`Command line: /usr/lib/phyml/bin/phyml-mpi --ancestral --no_memory_check -i /home/luke/Documents/Interspecies/extended_trees/extended_align.phylip -u /home/luke/Documents/Interspecies/extended_trees/extended_tree.newick -m HKY85 -c 4 -b 0 -v 0.000000 -o r -a 1.000000 /usr/lib/phyml/bin/phyml-mpi: unrecognized option '--leave_duplicates'
/usr/lib/phyml/bin/phyml-mpi: unrecognized option '--leave_duplicates'
/usr/lib/phyml/bin/phyml-mpi: unrecognized option '--leave_duplicates'
-f e --leave_duplicates 
/usr/lib/phyml/bin/phyml-mpi: unrecognized option '--leave_duplicates'
/usr/lib/phyml/bin/phyml-mpi: unrecognized option '--leave_duplicates'
/usr/lib/phyml/bin/phyml-mpi: unrecognized option '--leave_duplicates'`

`Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.`

`mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:` 

  `Process name: [[27310,1],2]
  Exit code:    1` 

This is my input:

`python ./xpas.py build -s nucl -b '/usr/bin/phyml' -w '/path/Interspecies' -r '/path/Interspecies/Ref_Alignment.fasta' -t '/path/LWreference_tree-NewickExportALT.nwk.newick' -k 10 -m HKY85 --use-unrooted`

Can anyone advise how to get around this issue?

Thanks

**Comment by nromashchenko** [comment]
Hello,

Thank you for reporting the issue.
> /usr/lib/phyml/bin/phyml-mpi: unrecognized option '--leave_duplicates' /usr/lib/phyml/bin/phyml-mpi: unrecognized option '--leave_duplicates'

It must be on the phyml side. Could you please indicate which version of phyml you are using?

**Comment by woodford87** [comment]
Hi. 

Thanks for replying! My Phyml version is the latest version (3:3.3.20170530+dfsg-2).

Thanks, I'll give raxml a try!

**Comment by nromashchenko** [comment]
> My Phyml version is the latest version (3:3.3.20170530+dfsg-2).

this is one of the versions of 2017, and the latest one is 3.3.20200621. You can either download it yourself [here](https://github.com/stephaneguindon/phyml) or just install it with bioconda.

**Comment by woodford87** [comment]
I can't seem to update the version on ubuntu beyond the 2017 version

**Comment by nromashchenko** [comment]
> I can't seem to update the version on ubuntu beyond the 2017 version

Yes, this is why I suggest using conda, there are multiple newer versions of phyml redistributed by bioconda: https://anaconda.org/bioconda/phyml
