### ISSUE TITLE
Missing <stdexcept> include 

### ISSUE THREAD

**Issue by blinard-BIOINFO** [phylo42/IPK#9]
@nromashchenko 

v0.3.1

```
In file included from xpas/src/xpas/phylo_tree.cpp:2:
xpas/include/xpas/phylo_tree.h: In constructor ‘xpas::visit_subtree<Iterator, Const>::visit_subtree(xpas::visit_subtree<Iterator, Const>::pointer)’: xpas/include/xpas/phylo_tree.h:293:28: error: ‘runtime_error’ is not a member of ‘std’
293 |  throw std::runtime_error("xpas::visit_subtree: root can not be null");
```
Fresh install of Clion, fresh clone of xpas repository. 
`#include <stdexcept>` needs to be added in `xpas/src/xpas/phylo_tree.cpp` otherwise the error above is throwed at compilation.

This appears to be new ? I never got this error on previous fresh installations.

**Comment by nromashchenko** [comment]
Fixed in v0.5.1
